import { Product } from '../../../types';

export const HOMBRE_IMAGES = {
  hombre: 'https://image.qwenlm.ai/public_source/881fbe0f-c2f7-44ca-82ed-bb676fcd173f/1b7986f18-09c4-46f2-9b15-9fc4a09bea4f.png',
  look1: 'https://image.qwenlm.ai/public_source/881fbe0f-c2f7-44ca-82ed-bb676fcd173f/1be63e46a-95f2-42bf-955e-861988de3e43.png',
  look2: 'https://image.qwenlm.ai/public_source/881fbe0f-c2f7-44ca-82ed-bb676fcd173f/11566497c-31c2-425f-8e4d-246557e3c060.png',
  look3: 'https://image.qwenlm.ai/public_source/881fbe0f-c2f7-44ca-82ed-bb676fcd173f/1973040b5-6379-4ac1-b876-0363987e6248.png',
  look4: 'https://image.qwenlm.ai/public_source/881fbe0f-c2f7-44ca-82ed-bb676fcd173f/1952a2899-ecfc-4366-a2c7-9fdc1e46731a.png',
  look5: 'https://image.qwenlm.ai/public_source/881fbe0f-c2f7-44ca-82ed-bb676fcd173f/18782fcbf-f189-427d-98ee-3229eb1cedd6.png',
  look6: 'https://image.qwenlm.ai/public_source/881fbe0f-c2f7-44ca-82ed-bb676fcd173f/10c755dad-2549-4dee-8b53-e393d47fb430.png',
  abrigoCamel: 'https://image.qwenlm.ai/public_source/881fbe0f-c2f7-44ca-82ed-bb676fcd173f/122fba2f5-b88e-4318-bf1b-10e7b57eeec2.png',
  carbon: 'https://image.qwenlm.ai/public_source/881fbe0f-c2f7-44ca-82ed-bb676fcd173f/149fd482b-487b-4fec-b926-dae329e1a6d1.png',
  oliva: 'https://image.qwenlm.ai/public_source/881fbe0f-c2f7-44ca-82ed-bb676fcd173f/1b7ec3070-dc94-4ac1-9ab2-8af96fd002a5.png',
  camisa: 'https://image.qwenlm.ai/public_source/881fbe0f-c2f7-44ca-82ed-bb676fcd173f/1cf220b76-fc97-4c34-b759-3630182728b8.png',
  knit: 'https://image.qwenlm.ai/public_source/881fbe0f-c2f7-44ca-82ed-bb676fcd173f/1fce9e2be-67bd-4c29-a459-922edf704cc3.png',
  pantCarbon: 'https://image.qwenlm.ai/public_source/881fbe0f-c2f7-44ca-82ed-bb676fcd173f/1aaa0e83d-cb20-423c-90cc-f9895617c186.png',
  arena: 'https://image.qwenlm.ai/public_source/881fbe0f-c2f7-44ca-82ed-bb676fcd173f/1c1f2f77b-130b-4cfa-a82c-86c266c74066.png',
  denim: 'https://image.qwenlm.ai/public_source/881fbe0f-c2f7-44ca-82ed-bb676fcd173f/15209f967-f7f3-4e39-a968-0e43599c18e8.png',
  botasCuero: 'https://image.qwenlm.ai/public_source/881fbe0f-c2f7-44ca-82ed-bb676fcd173f/14bf9680b-0752-45b8-8862-ebc21a5bb0d3.png',
  botasCrema: 'https://image.qwenlm.ai/public_source/881fbe0f-c2f7-44ca-82ed-bb676fcd173f/19dcc03ee-b85c-46c7-820f-db90c526e3f1.png',
  sneakers: 'https://image.qwenlm.ai/public_source/881fbe0f-c2f7-44ca-82ed-bb676fcd173f/18eefe980-4079-4f21-9c76-eda5a7daa3b1.png',
  parMostaza: 'https://image.qwenlm.ai/public_source/881fbe0f-c2f7-44ca-82ed-bb676fcd173f/161b1bfc1-08ae-4a0f-82d1-7cc20c84a401.png',
  parBorgona: 'https://image.qwenlm.ai/public_source/881fbe0f-c2f7-44ca-82ed-bb676fcd173f/1494b52e9-93ad-49ba-8230-c28246df8473.png',
  bufandaTeal: 'https://image.qwenlm.ai/public_source/881fbe0f-c2f7-44ca-82ed-bb676fcd173f/1fbc849de-3fc0-4b22-ba21-436664cf850e.png',
  bucket: 'https://image.qwenlm.ai/public_source/881fbe0f-c2f7-44ca-82ed-bb676fcd173f/1e07e9367-3d7e-4e5c-98dc-a7cbe4d83124.png',
  guantes: 'https://image.qwenlm.ai/public_source/881fbe0f-c2f7-44ca-82ed-bb676fcd173f/141b975dd-80af-4377-8053-6a540060ed7f.png',
  mochCamel: 'https://image.qwenlm.ai/public_source/881fbe0f-c2f7-44ca-82ed-bb676fcd173f/1f3b87669-b4fa-4caf-8c1a-7de67be86b0f.png',
  mochOliva: 'https://image.qwenlm.ai/public_source/881fbe0f-c2f7-44ca-82ed-bb676fcd173f/17db3a775-9c44-4a20-9fe8-c590c5220799.png',
  mochCarbon: 'https://image.qwenlm.ai/public_source/881fbe0f-c2f7-44ca-82ed-bb676fcd173f/1919c12bc-5662-4ace-8754-4c178666ee61.png',
  mochMostaza: 'https://image.qwenlm.ai/public_source/881fbe0f-c2f7-44ca-82ed-bb676fcd173f/1909ec18d-bc62-4f8c-854a-3b595d0e8f63.png',
  mochCuero: 'https://image.qwenlm.ai/public_source/881fbe0f-c2f7-44ca-82ed-bb676fcd173f/108f8687c-77d4-4bee-8550-cba45e2c1e7f.png',
  gorro: 'https://image.qwenlm.ai/public_source/881fbe0f-c2f7-44ca-82ed-bb676fcd173f/127b45dd6-2a7e-4170-ba60-52dd5ecd1fa6.png',
  cinturon: 'https://image.qwenlm.ai/public_source/881fbe0f-c2f7-44ca-82ed-bb676fcd173f/15155cbd4-ee55-4d44-88b9-5e1bc64c0fdb.png',
  calcetines: 'https://image.qwenlm.ai/public_source/881fbe0f-c2f7-44ca-82ed-bb676fcd173f/1311eaa51-a26f-4783-86cf-421a41304ac9.png',
  billetera: 'https://image.qwenlm.ai/public_source/881fbe0f-c2f7-44ca-82ed-bb676fcd173f/183c1089d-2770-402a-91de-eb067df34503.png',
  bufandaMostaza: 'https://image.qwenlm.ai/public_source/881fbe0f-c2f7-44ca-82ed-bb676fcd173f/15cd70f39-30b6-47a6-afc1-018f904d4853.png',
  chaleco: 'https://image.qwenlm.ai/public_source/881fbe0f-c2f7-44ca-82ed-bb676fcd173f/18a0e6dfb-6508-4ba3-9ca1-47589df53294.png',
  sueterTeal: 'https://image.qwenlm.ai/public_source/881fbe0f-c2f7-44ca-82ed-bb676fcd173f/1455bcb9a-a7e6-4ff2-af8f-ca9f305e8d00.png',
  camisaMostaza: 'https://image.qwenlm.ai/public_source/881fbe0f-c2f7-44ca-82ed-bb676fcd173f/1a63f1938-7062-4d93-be77-f62f0d16a19b.png',
  chaqDenim: 'https://image.qwenlm.ai/public_source/881fbe0f-c2f7-44ca-82ed-bb676fcd173f/1b46f8c66-8f01-49d6-8127-c836f572c416.png'
};

export const HOMBRE_PRODUCTS: Product[] = [
  {
    id: 'h-01',
    name: 'Sobretodo Camel',
    brand: 'MANTA',
    category: 'Abrigos',
    family: 'hombre',
    price: 175,
    priceFormatted: '$175 USD',
    colors: 'Camel / lana',
    sizes: ['S', 'M', 'L', 'XL'],
    img: HOMBRE_IMAGES.hombre,
    image: HOMBRE_IMAGES.hombre,
    isNew: true,
    probador: true,
    tag: 'Editorial',
    subtitle: 'Sobretodo clásico en lana virgen repelente al agua, silueta recta estructurada.',
    editorialProvenance: 'Hombre 05 · Look 01',
    availability: 'in-stock'
  },
  {
    id: 'h-02',
    name: 'Sobretodo Carbón',
    brand: 'MANTA',
    category: 'Abrigos',
    family: 'hombre',
    price: 185,
    priceFormatted: '$185 USD',
    colors: 'Negro carbón',
    sizes: ['S', 'M', 'L', 'XL'],
    img: HOMBRE_IMAGES.carbon,
    image: HOMBRE_IMAGES.carbon,
    isNew: true,
    probador: true,
    tag: 'Sastrería',
    subtitle: 'Lana densa peinada con tratamiento hidrófugo y forro de cupro transpirable.',
    editorialProvenance: 'Hombre 05 · Look 06',
    availability: 'in-stock'
  },
  {
    id: 'h-03',
    name: 'Abrigo Camel Doble',
    brand: 'MANTA',
    category: 'Abrigos',
    family: 'hombre',
    price: 180,
    priceFormatted: '$180 USD',
    colors: 'Camel / beige',
    sizes: ['S', 'M', 'L', 'XL'],
    img: HOMBRE_IMAGES.abrigoCamel,
    image: HOMBRE_IMAGES.abrigoCamel,
    probador: false,
    subtitle: 'Doble botonadura con solapa ancha y corte envolvente para días fríos.',
    editorialProvenance: 'Hombre 05',
    availability: 'in-stock'
  },
  {
    id: 'h-04',
    name: 'Rain Jacket Oliva',
    brand: 'NORTE',
    category: 'Abrigos',
    family: 'hombre',
    price: 98,
    priceFormatted: '$98 USD',
    colors: 'Oliva técnico',
    sizes: ['S', 'M', 'L', 'XL'],
    img: HOMBRE_IMAGES.oliva,
    image: HOMBRE_IMAGES.oliva,
    isNew: true,
    probador: true,
    tag: 'Técnico',
    subtitle: 'Chaqueta impermeable ligera con costuras termoselladas y bolsillos estancos.',
    editorialProvenance: 'Hombre 05 · Look 02',
    availability: 'in-stock'
  },
  {
    id: 'h-05',
    name: 'Chaleco Camel Ejecutivo',
    brand: 'MANTA',
    category: 'Abrigos',
    family: 'hombre',
    price: 85,
    priceFormatted: '$85 USD',
    colors: 'Camel / sastre',
    sizes: ['S', 'M', 'L', 'XL'],
    img: HOMBRE_IMAGES.chaleco,
    image: HOMBRE_IMAGES.chaleco,
    isNew: true,
    probador: true,
    tag: 'Sastrería',
    subtitle: 'Chaleco sastre en lana peinada con espalda de satén y hebilla de ajuste.',
    editorialProvenance: 'Hombre 05 · Look 05',
    availability: 'in-stock'
  },
  {
    id: 'h-06',
    name: 'Chaqueta Denim Nocturna',
    brand: 'BRUMA',
    category: 'Abrigos',
    family: 'hombre',
    price: 92,
    priceFormatted: '$92 USD',
    colors: 'Índigo lavado',
    sizes: ['S', 'M', 'L', 'XL'],
    img: HOMBRE_IMAGES.chaqDenim,
    image: HOMBRE_IMAGES.chaqDenim,
    isNew: true,
    probador: true,
    tag: 'Urbano',
    subtitle: 'Mezclilla pesada de 14oz tratada con cera vegetal repelente al agua.',
    editorialProvenance: 'Hombre 05 · Look 03',
    availability: 'in-stock'
  },
  {
    id: 'h-07',
    name: 'Camisa Técnica Blanca',
    brand: 'MANTA',
    category: 'Camisas',
    family: 'hombre',
    price: 58,
    priceFormatted: '$58 USD',
    colors: 'Blanco repelente',
    sizes: ['S', 'M', 'L', 'XL'],
    img: HOMBRE_IMAGES.camisa,
    image: HOMBRE_IMAGES.camisa,
    isNew: true,
    probador: true,
    subtitle: 'Popelina de algodón de fibra larga con acabado antimanchas y secado ultra rápido.',
    editorialProvenance: 'Hombre 05 · Look 01',
    availability: 'in-stock'
  },
  {
    id: 'h-08',
    name: 'Camisa Mostaza Cielo',
    brand: 'MANTA',
    category: 'Camisas',
    family: 'hombre',
    price: 56,
    priceFormatted: '$56 USD',
    colors: 'Mostaza franela',
    sizes: ['S', 'M', 'L', 'XL'],
    img: HOMBRE_IMAGES.camisaMostaza,
    image: HOMBRE_IMAGES.camisaMostaza,
    isNew: true,
    probador: true,
    subtitle: 'Franela suave afelpada de algodón orgánico, botones de corozo natural.',
    editorialProvenance: 'Hombre 05 · Look 04',
    availability: 'in-stock'
  },
  {
    id: 'h-09',
    name: 'Knit Avena Bruma',
    brand: 'BRUMA',
    category: 'Camisas',
    family: 'hombre',
    price: 64,
    priceFormatted: '$64 USD',
    colors: 'Avena / lana',
    sizes: ['S', 'M', 'L', 'XL'],
    img: HOMBRE_IMAGES.knit,
    image: HOMBRE_IMAGES.knit,
    probador: true,
    subtitle: 'Suéter de cuello redondo en punto canalé grueso con lana merina virgen.',
    editorialProvenance: 'Hombre 05 · Look 02',
    availability: 'in-stock'
  },
  {
    id: 'h-10',
    name: 'Suéter Teal Monzón',
    brand: 'BRUMA',
    category: 'Camisas',
    family: 'hombre',
    price: 66,
    priceFormatted: '$66 USD',
    colors: 'Teal profundo',
    sizes: ['S', 'M', 'L', 'XL'],
    img: HOMBRE_IMAGES.sueterTeal,
    image: HOMBRE_IMAGES.sueterTeal,
    isNew: true,
    probador: true,
    subtitle: 'Tejido denso en lana y cachemira color teal profundo, puños elásticos.',
    editorialProvenance: 'Hombre 05 · Look 03',
    availability: 'in-stock'
  },
  {
    id: 'h-11',
    name: 'Pantalón Carbón',
    brand: 'MANTA',
    category: 'Pantalones',
    family: 'hombre',
    price: 72,
    priceFormatted: '$72 USD',
    colors: 'Gris carbón',
    sizes: ['S', 'M', 'L', 'XL'],
    img: HOMBRE_IMAGES.pantCarbon,
    image: HOMBRE_IMAGES.pantCarbon,
    probador: true,
    subtitle: 'Pantalón sastre con pinzas frontales y tejido de lana fría stretch.',
    editorialProvenance: 'Hombre 05 · Look 01',
    availability: 'in-stock'
  },
  {
    id: 'h-12',
    name: 'Pantalón Arena',
    brand: 'NORTE',
    category: 'Pantalones',
    family: 'hombre',
    price: 68,
    priceFormatted: '$68 USD',
    colors: 'Arena / chino',
    sizes: ['S', 'M', 'L', 'XL'],
    img: HOMBRE_IMAGES.arena,
    image: HOMBRE_IMAGES.arena,
    probador: true,
    subtitle: 'Chino funcional en twill de algodón impermeable con refuerzo en entrepierna.',
    editorialProvenance: 'Hombre 05 · Look 02',
    availability: 'in-stock'
  },
  {
    id: 'h-13',
    name: 'Denim Bruma',
    brand: 'BRUMA',
    category: 'Pantalones',
    family: 'hombre',
    price: 76,
    priceFormatted: '$76 USD',
    colors: 'Índigo rain-wash',
    sizes: ['S', 'M', 'L', 'XL'],
    img: HOMBRE_IMAGES.denim,
    image: HOMBRE_IMAGES.denim,
    probador: true,
    subtitle: 'Jeans de corte recto con lavado a la piedra inspirado en la bruma de lluvia.',
    editorialProvenance: 'Hombre 05 · Look 03',
    availability: 'in-stock'
  },
  {
    id: 'h-14',
    name: 'Mochila Camel Ejecutivo',
    brand: 'MANTA',
    category: 'Mochilas',
    family: 'hombre',
    price: 88,
    priceFormatted: '$88 USD',
    colors: 'Cuero camel / latón',
    sizes: ['20L', '25L'],
    img: HOMBRE_IMAGES.mochCamel,
    image: HOMBRE_IMAGES.mochCamel,
    isNew: true,
    probador: true,
    tag: 'Fila Mochilas',
    subtitle: 'Cuero curtido vegetal camel con herrajes de latón macizo y funda para laptop.',
    editorialProvenance: 'Hombre 05 · Look 01',
    availability: 'in-stock'
  },
  {
    id: 'h-15',
    name: 'Mochila Oliva Técnica',
    brand: 'NORTE',
    category: 'Mochilas',
    family: 'hombre',
    price: 76,
    priceFormatted: '$76 USD',
    colors: 'Oliva impermeable',
    sizes: ['20L', '25L'],
    img: HOMBRE_IMAGES.mochOliva,
    image: HOMBRE_IMAGES.mochOliva,
    isNew: true,
    probador: true,
    tag: 'Fila Mochilas',
    subtitle: 'Nylon balístico impermeable con cremalleras termoselladas y espalda acolchada.',
    editorialProvenance: 'Hombre 05 · Look 02',
    availability: 'in-stock'
  },
  {
    id: 'h-16',
    name: 'Mochila Carbón Urbana',
    brand: 'BRUMA',
    category: 'Mochilas',
    family: 'hombre',
    price: 82,
    priceFormatted: '$82 USD',
    colors: 'Carbón mate',
    sizes: ['20L', '25L'],
    img: HOMBRE_IMAGES.mochCarbon,
    image: HOMBRE_IMAGES.mochCarbon,
    isNew: true,
    probador: true,
    tag: 'Fila Mochilas',
    subtitle: 'Lona encerada mate carbón con cierre enrollable magnético Fidlock.',
    editorialProvenance: 'Hombre 05 · Look 03',
    availability: 'in-stock'
  },
  {
    id: 'h-17',
    name: 'Mochila Mostaza Cielo',
    brand: 'LLUVIA LAB',
    category: 'Mochilas',
    family: 'hombre',
    price: 70,
    priceFormatted: '$70 USD',
    colors: 'Mostaza roll-top',
    sizes: ['20L', '25L'],
    img: HOMBRE_IMAGES.mochMostaza,
    image: HOMBRE_IMAGES.mochMostaza,
    isNew: true,
    probador: true,
    tag: 'Fila Mochilas',
    subtitle: 'Roll-top en lona técnica amarilla reflectante con costuras de alta visibilidad.',
    editorialProvenance: 'Hombre 05 · Look 04',
    availability: 'in-stock'
  },
  {
    id: 'h-18',
    name: 'Mochila Cuero Terra',
    brand: 'TERRA',
    category: 'Mochilas',
    family: 'hombre',
    price: 95,
    priceFormatted: '$95 USD',
    colors: 'Cuero castaño',
    sizes: ['20L', '25L'],
    img: HOMBRE_IMAGES.mochCuero,
    image: HOMBRE_IMAGES.mochCuero,
    isNew: true,
    probador: true,
    tag: 'Fila Mochilas',
    subtitle: 'Cuero flor curtido artesanal con doble bolsillo exterior y tirantes de cuero grueso.',
    editorialProvenance: 'Hombre 05 · Look 05',
    availability: 'in-stock'
  },
  {
    id: 'h-19',
    name: 'Botas Terra Cuero',
    brand: 'TERRA',
    category: 'Calzado',
    family: 'hombre',
    price: 110,
    priceFormatted: '$110 USD',
    colors: 'Cuero / crema',
    sizes: ['40', '41', '42', '43'],
    img: HOMBRE_IMAGES.botasCuero,
    image: HOMBRE_IMAGES.botasCuero,
    probador: true,
    subtitle: 'Botas de caña media en cuero engrasado impermeable con suela Vibram de charco.',
    editorialProvenance: 'Hombre 05 · Look 01',
    availability: 'in-stock'
  },
  {
    id: 'h-20',
    name: 'Botas Crema',
    brand: 'MANTA',
    category: 'Calzado',
    family: 'hombre',
    price: 95,
    priceFormatted: '$95 USD',
    colors: 'Crema / agua',
    sizes: ['40', '41', '42', '43'],
    img: HOMBRE_IMAGES.botasCrema,
    image: HOMBRE_IMAGES.botasCrema,
    probador: true,
    subtitle: 'Botines chelsea en caucho natural crema con elásticos laterales estancos.',
    editorialProvenance: 'Hombre 05 · Look 03',
    availability: 'in-stock'
  },
  {
    id: 'h-21',
    name: 'Sneakers Bruma Blanco',
    brand: 'BRUMA',
    category: 'Calzado',
    family: 'hombre',
    price: 120,
    priceFormatted: '$120 USD',
    colors: 'Blanco / gota',
    sizes: ['40', '41', '42', '43'],
    img: HOMBRE_IMAGES.sneakers,
    image: HOMBRE_IMAGES.sneakers,
    probador: true,
    subtitle: 'Zapatillas de piel con membrana impermeable interna y suela de tracción en mojado.',
    editorialProvenance: 'Hombre 05 · Look 02',
    availability: 'in-stock'
  },
  {
    id: 'h-22',
    name: 'Paraguas Mostaza',
    brand: 'LLUVIA LAB',
    category: 'Accesorios',
    family: 'hombre',
    price: 45,
    priceFormatted: '$45 USD',
    colors: 'Mostaza / madera',
    sizes: ['ÚNICO'],
    img: HOMBRE_IMAGES.parMostaza,
    image: HOMBRE_IMAGES.parMostaza,
    probador: true,
    subtitle: 'Paraguas bastón con mango curvo de madera de nogal y varillas dobles anti-viento.',
    editorialProvenance: 'Hombre 05 · Look 04',
    availability: 'in-stock'
  },
  {
    id: 'h-23',
    name: 'Paraguas Borgoña',
    brand: 'LLUVIA LAB',
    category: 'Accesorios',
    family: 'hombre',
    price: 45,
    priceFormatted: '$45 USD',
    colors: 'Borgoña / madera',
    sizes: ['ÚNICO'],
    img: HOMBRE_IMAGES.parBorgona,
    image: HOMBRE_IMAGES.parBorgona,
    isNew: true,
    probador: true,
    subtitle: 'Paraguas clásico en tela teflonada borgoña con remates de latón cepillado.',
    editorialProvenance: 'Hombre 05 · Look 01',
    availability: 'in-stock'
  },
  {
    id: 'h-24',
    name: 'Bufanda Terra Teal',
    brand: 'TERRA',
    category: 'Accesorios',
    family: 'hombre',
    price: 38,
    priceFormatted: '$38 USD',
    colors: 'Lana teal',
    sizes: ['ÚNICO'],
    img: HOMBRE_IMAGES.bufandaTeal,
    image: HOMBRE_IMAGES.bufandaTeal,
    probador: true,
    subtitle: 'Bufanda extra ancha en lana virgen con flecos trenzados a mano en tono teal.',
    editorialProvenance: 'Hombre 05 · Look 03',
    availability: 'in-stock'
  },
  {
    id: 'h-25',
    name: 'Bufanda Mostaza',
    brand: 'LLUVIA LAB',
    category: 'Accesorios',
    family: 'hombre',
    price: 36,
    priceFormatted: '$36 USD',
    colors: 'Lana mostaza',
    sizes: ['ÚNICO'],
    img: HOMBRE_IMAGES.bufandaMostaza,
    image: HOMBRE_IMAGES.bufandaMostaza,
    isNew: true,
    probador: true,
    subtitle: 'Lana peinada hipoalergénica con tejido gofrado térmico y bordes reforzados.',
    editorialProvenance: 'Hombre 05 · Look 04',
    availability: 'in-stock'
  },
  {
    id: 'h-26',
    name: 'Bucket Mostaza',
    brand: 'LLUVIA LAB',
    category: 'Accesorios',
    family: 'hombre',
    price: 32,
    priceFormatted: '$32 USD',
    colors: 'Mostaza',
    sizes: ['ÚNICO'],
    img: HOMBRE_IMAGES.bucket,
    image: HOMBRE_IMAGES.bucket,
    probador: true,
    subtitle: 'Gorro pescador repelente al agua con forro interior transpirable y cinta reflectante.',
    editorialProvenance: 'Hombre 05 · Look 04',
    availability: 'in-stock'
  },
  {
    id: 'h-27',
    name: 'Gorro Knit Carbón',
    brand: 'BRUMA',
    category: 'Accesorios',
    family: 'hombre',
    price: 26,
    priceFormatted: '$26 USD',
    colors: 'Carbón tejido',
    sizes: ['ÚNICO'],
    img: HOMBRE_IMAGES.gorro,
    image: HOMBRE_IMAGES.gorro,
    isNew: true,
    probador: true,
    subtitle: 'Beanie clásico en canalé de lana merina con vuelta doble y parche tonal.',
    editorialProvenance: 'Hombre 05 · Look 06',
    availability: 'in-stock'
  },
  {
    id: 'h-28',
    name: 'Guantes Cuero',
    brand: 'TERRA',
    category: 'Accesorios',
    family: 'hombre',
    price: 42,
    priceFormatted: '$42 USD',
    colors: 'Cuero castaño',
    sizes: ['ÚNICO'],
    img: HOMBRE_IMAGES.guantes,
    image: HOMBRE_IMAGES.guantes,
    probador: true,
    subtitle: 'Guantes de piel de cordero encerada con forro interior térmico de cachemira.',
    editorialProvenance: 'Hombre 05 · Look 05',
    availability: 'in-stock'
  },
  {
    id: 'h-29',
    name: 'Cinturón Cuero Terra',
    brand: 'TERRA',
    category: 'Accesorios',
    family: 'hombre',
    price: 48,
    priceFormatted: '$48 USD',
    colors: 'Cuero / latón',
    sizes: ['ÚNICO'],
    img: HOMBRE_IMAGES.cinturon,
    image: HOMBRE_IMAGES.cinturon,
    isNew: true,
    probador: true,
    subtitle: 'Cinturón artesanal de 3.5cm en cuero grueso con hebilla de latón envejecido.',
    editorialProvenance: 'Hombre 05 · Look 05',
    availability: 'in-stock'
  },
  {
    id: 'h-30',
    name: 'Billetera Borgoña',
    brand: 'TERRA',
    category: 'Accesorios',
    family: 'hombre',
    price: 35,
    priceFormatted: '$35 USD',
    colors: 'Borgoña cosido',
    sizes: ['ÚNICO'],
    img: HOMBRE_IMAGES.billetera,
    image: HOMBRE_IMAGES.billetera,
    isNew: true,
    probador: true,
    subtitle: 'Billetera plegable compacta en piel borgoña con protección RFID y 6 ranuras.',
    editorialProvenance: 'Hombre 05 · Look 01',
    availability: 'in-stock'
  },
  {
    id: 'h-31',
    name: 'Calcetines Trío Lluvia',
    brand: 'LLUVIA LAB',
    category: 'Accesorios',
    family: 'hombre',
    price: 22,
    priceFormatted: '$22 USD',
    colors: 'Mostaza/teal/borgoña',
    sizes: ['ÚNICO'],
    img: HOMBRE_IMAGES.calcetines,
    image: HOMBRE_IMAGES.calcetines,
    isNew: true,
    probador: true,
    subtitle: 'Pack de 3 calcetines altos en algodón peinado con soporte elástico y puntera reforzada.',
    editorialProvenance: 'Hombre 05 · Look 02',
    availability: 'in-stock'
  }
];

export const HOMBRE_PRODUCTS_BY_NAME: Record<string, Product> = {};
HOMBRE_PRODUCTS.forEach((p) => {
  HOMBRE_PRODUCTS_BY_NAME[p.name] = p;
});

export interface HombreOutfit {
  name: string;
  desc: string;
  img: string;
  colors: {
    coat: string;
    pants: string;
    shoes: string;
    scarf: string | null;
    hat: string | null;
    umbrella: string | null;
    pack: string | null;
  };
  items: string[];
  dots: Record<string, string>;
}

export const HOMBRE_OUTFITS: HombreOutfit[] = [
  {
    name: 'Ejecutivo Lluvia',
    desc: 'Sastrería suave en camel con paraguas y mochila de cuero: el clásico que nunca falla.',
    img: HOMBRE_IMAGES.look1,
    colors: {
      coat: '#c8956c',
      pants: '#2e3440',
      shoes: '#6b4a33',
      scarf: null,
      hat: null,
      umbrella: '#7a2e2a',
      pack: '#b98045'
    },
    items: [
      'Sobretodo Camel',
      'Camisa Técnica Blanca',
      'Pantalón Carbón',
      'Botas Terra Cuero',
      'Paraguas Borgoña',
      'Mochila Camel Ejecutivo',
      'Billetera Borgoña'
    ],
    dots: { 'Camisa Técnica Blanca': '#e8e6e1' }
  },
  {
    name: 'Norte Urbano',
    desc: 'Oliva técnico sobre arena con mochila impermeable: funcional y cálido para la ciudad mojada.',
    img: HOMBRE_IMAGES.look2,
    colors: {
      coat: '#5a6b4f',
      pants: '#cbb894',
      shoes: '#e8e6e1',
      scarf: null,
      hat: null,
      umbrella: null,
      pack: '#5a6b4f'
    },
    items: [
      'Rain Jacket Oliva',
      'Knit Avena Bruma',
      'Pantalón Arena',
      'Sneakers Bruma Blanco',
      'Mochila Oliva Técnica',
      'Calcetines Trío Lluvia'
    ],
    dots: { 'Knit Avena Bruma': '#d8c6a8', 'Calcetines Trío Lluvia': '#2f8f8a' }
  },
  {
    name: 'Monzón Nocturno',
    desc: 'Denim sobre denim con acento teal y mochila carbón: noche, lluvia y neón.',
    img: HOMBRE_IMAGES.look3,
    colors: {
      coat: '#41506b',
      pants: '#4a5a74',
      shoes: '#e3ddd2',
      scarf: '#2f8f8a',
      hat: null,
      umbrella: null,
      pack: '#3a3f45'
    },
    items: [
      'Chaqueta Denim Nocturna',
      'Suéter Teal Monzón',
      'Denim Bruma',
      'Botas Crema',
      'Bufanda Terra Teal',
      'Mochila Carbón Urbana'
    ],
    dots: { 'Botas Crema': '#e3ddd2' }
  },
  {
    name: 'Cielo Mostaza',
    desc: 'Dosis doble de mostaza sobre denim: optimismo impermeable de la cabeza a la mochila.',
    img: HOMBRE_IMAGES.look4,
    colors: {
      coat: '#d9a441',
      pants: '#4a5a74',
      shoes: '#e8e6e1',
      scarf: null,
      hat: '#d9a441',
      umbrella: '#d9a441',
      pack: '#d9a441'
    },
    items: [
      'Camisa Mostaza Cielo',
      'Denim Bruma',
      'Sneakers Bruma Blanco',
      'Bucket Mostaza',
      'Bufanda Mostaza',
      'Paraguas Mostaza',
      'Mochila Mostaza Cielo'
    ],
    dots: {}
  },
  {
    name: 'Terra Café',
    desc: 'Camel, avena y cuero con mochila castaña: la paleta del bosque llevada al asfalto.',
    img: HOMBRE_IMAGES.look5,
    colors: {
      coat: '#c8956c',
      pants: '#cbb894',
      shoes: '#5b3a29',
      scarf: null,
      hat: null,
      umbrella: null,
      pack: '#5b3a29'
    },
    items: [
      'Chaleco Camel Ejecutivo',
      'Knit Avena Bruma',
      'Pantalón Arena',
      'Botas Terra Cuero',
      'Guantes Cuero',
      'Cinturón Cuero Terra',
      'Mochila Cuero Terra'
    ],
    dots: { 'Knit Avena Bruma': '#d8c6a8' }
  },
  {
    name: 'Andina Borgoña',
    desc: 'Carbón profundo con borgoña de madera y gorro tejido: elegancia de altura bajo la lluvia.',
    img: HOMBRE_IMAGES.look6,
    colors: {
      coat: '#23272e',
      pants: '#262b33',
      shoes: '#6b4a33',
      scarf: null,
      hat: '#3a3f45',
      umbrella: '#7a2e2a',
      pack: '#3a3f45'
    },
    items: [
      'Sobretodo Carbón',
      'Camisa Técnica Blanca',
      'Pantalón Carbón',
      'Botas Terra Cuero',
      'Paraguas Borgoña',
      'Gorro Knit Carbón',
      'Mochila Carbón Urbana'
    ],
    dots: { 'Camisa Técnica Blanca': '#e8e6e1' }
  }
];

export const HOMBRE_PROBADOR_SET: Record<string, boolean> = {};
HOMBRE_OUTFITS.forEach((o) => {
  o.items.forEach((itemName) => {
    HOMBRE_PROBADOR_SET[itemName] = true;
  });
});
