import { StoreProduct, StoreBrand, StoreCategoryItem } from './storeTypes';
import { HOMBRE_PRODUCTS, HOMBRE_IMAGES } from './hombre/hombreData';

export const STORE_BRANDS: StoreBrand[] = [
  {
    id: 'manta',
    name: 'Manta',
    status: 'available',
    visualVariant: 'border-[#f2c14e]/30 bg-[#f2c14e]/10 text-[#f2c14e] hover:border-[#f2c14e]',
    tagline: 'Línea de la Casa'
  },
  {
    id: 'norte',
    name: 'Norte',
    status: 'available',
    visualVariant: 'border-[#89a8b2]/30 bg-[#89a8b2]/10 text-[#89a8b2] hover:border-[#89a8b2]',
    tagline: 'Prendas Térmicas'
  },
  {
    id: 'lluvia-lab',
    name: 'Lluvia Lab',
    status: 'available',
    visualVariant: 'border-[#a3b899]/30 bg-[#a3b899]/10 text-[#a3b899] hover:border-[#a3b899]',
    tagline: 'Textiles Repelentes'
  },
  {
    id: 'terra',
    name: 'Terra',
    status: 'available',
    visualVariant: 'border-[#d8a47f]/30 bg-[#d8a47f]/10 text-[#d8a47f] hover:border-[#d8a47f]',
    tagline: 'Calzado Todo Terreno'
  },
  {
    id: 'bruma',
    name: 'Bruma',
    status: 'available',
    visualVariant: 'border-[#b8b0c8]/30 bg-[#b8b0c8]/10 text-[#b8b0c8] hover:border-[#b8b0c8]',
    tagline: 'Lana & Tejidos'
  },
  {
    id: 'valle',
    name: 'Valle',
    status: 'available',
    visualVariant: 'border-[#e5b299]/30 bg-[#e5b299]/10 text-[#e5b299] hover:border-[#e5b299]',
    tagline: 'Algodón Orgánico'
  },
  {
    id: 'andina',
    name: 'Andina',
    status: 'available',
    visualVariant: 'border-[#c5a880]/30 bg-[#c5a880]/10 text-[#c5a880] hover:border-[#c5a880]',
    tagline: 'Fibras Naturales'
  },
  {
    id: 'cielo',
    name: 'Cielo',
    status: 'soon',
    visualVariant: 'border-[#98b4d4]/30 bg-[#98b4d4]/10 text-[#98b4d4] hover:border-[#98b4d4]',
    tagline: 'Próximo Drop'
  },
  {
    id: 'sur',
    name: 'Sur',
    status: 'soon',
    visualVariant: 'border-[#e0a96d]/30 bg-[#e0a96d]/10 text-[#e0a96d] hover:border-[#e0a96d]',
    tagline: 'Próximo Drop'
  },
  {
    id: 'paramo',
    name: 'Páramo',
    status: 'soon',
    visualVariant: 'border-[#96a88b]/30 bg-[#96a88b]/10 text-[#96a88b] hover:border-[#96a88b]',
    tagline: 'Próximo Drop'
  },
  {
    id: 'rocio',
    name: 'Rocío',
    status: 'soon',
    visualVariant: 'border-[#d9b48f]/30 bg-[#d9b48f]/10 text-[#d9b48f] hover:border-[#d9b48f]',
    tagline: 'Próximo Drop'
  },
  {
    id: 'monzon',
    name: 'Monzón',
    status: 'soon',
    visualVariant: 'border-[#a3c9a8]/30 bg-[#a3c9a8]/10 text-[#a3c9a8] hover:border-[#a3c9a8]',
    tagline: 'Próximo Drop'
  }
];

export const BRANDS_LIST = [
  'MANTA',
  'NORTE',
  'LLUVIA LAB',
  'TERRA',
  'BRUMA',
  'VALLE',
  'ANDINA',
  'CIELO',
  'SUR',
  'PÁRAMO',
  'ROCÍO',
  'MONZÓN'
];

export const EDITORIAL_STORE_PRODUCTS: StoreProduct[] = [
  {
    id: 'manta-01',
    name: 'Paraguas Mostaza Clásico',
    brand: 'Manta',
    category: 'Accesorios',
    family: 'unisex',
    price: 680,
    priceFormatted: '$680 MXN',
    colors: 'Mostaza / Madera natural',
    image: 'https://image.qwenlm.ai/public_source/ba5bbbd1-0f81-4568-a13e-b8a4583800d2/137b0daca-0ff3-4489-b0bb-75f759fe7fda.png',
    isNew: true,
    tag: 'Drop Semanal',
    subtitle: 'Varillaje reforzado en fibra de vidrio y mango ergonómico de madera pulida.',
    editorialProvenance: 'Agosto · Look 01',
    availability: 'in-stock'
  },
  {
    id: 'valle-01',
    name: 'Impermeable Terracota Fino',
    brand: 'Valle',
    category: 'Ropa',
    family: 'mujer',
    price: 1450,
    priceFormatted: '$1,450 MXN',
    colors: 'Terracota / Ocre',
    sizes: ['CH', 'M', 'G', 'XG'],
    image: 'https://image.qwenlm.ai/public_source/ba5bbbd1-0f81-4568-a13e-b8a4583800d2/1c0e12018-da51-40f4-bb31-83caa5e82f13.png',
    isNew: true,
    tag: 'Novedad',
    subtitle: 'Membrana repelente transpirable con forro interior en algodón peinado suave.',
    editorialProvenance: 'Agosto · Look 02',
    availability: 'in-stock'
  },
  {
    id: 'terra-01',
    name: 'Botas de Lluvia Humo',
    brand: 'Terra',
    category: 'Calzado',
    family: 'hombre',
    price: 980,
    priceFormatted: '$980 MXN',
    colors: 'Gris Humo / Suela Ámbar',
    sizes: ['25 MX', '26 MX', '27 MX', '28 MX', '29 MX'],
    image: 'https://image.qwenlm.ai/public_source/ba5bbbd1-0f81-4568-a13e-b8a4583800d2/1918f64ff-f2f2-49a4-9534-4850ea64937b.png',
    tag: 'Edición Limitada',
    subtitle: 'Caucho vulcanizado natural con plantilla anatómica y suela antideslizante.',
    editorialProvenance: 'Agosto · Look 03',
    availability: 'limited'
  },
  {
    id: 'manta-02',
    name: 'Sastre Marfil Bordado Chiapas',
    brand: 'Manta',
    category: 'Ropa',
    family: 'mujer',
    price: 2400,
    priceFormatted: '$2,400 MXN',
    colors: 'Marfil / Hilos Carmín & Oro',
    sizes: ['CH', 'M', 'G'],
    image: 'https://image.qwenlm.ai/public_source/ba5bbbd1-0f81-4568-a13e-b8a4583800d2/1b997c99b-506e-49b7-8179-b71cf840e1cd.png',
    isNew: true,
    tag: 'Artesanal',
    subtitle: 'Sastrería urbana con hilo bordado a mano por maestras artesanas de Chiapas.',
    editorialProvenance: 'Septiembre · Look 01',
    availability: 'in-stock'
  },
  {
    id: 'manta-03',
    name: 'Sastre Gala Charra Medianoche',
    brand: 'Manta',
    category: 'Ropa',
    family: 'hombre',
    price: 2650,
    priceFormatted: '$2,650 MXN',
    colors: 'Azul Medianoche / Botonería Plata',
    sizes: ['CH', 'M', 'G', 'XG'],
    image: 'https://image.qwenlm.ai/public_source/ba5bbbd1-0f81-4568-a13e-b8a4583800d2/17b82f4ed-9348-4e41-bd71-7266416f3364.png',
    tag: 'Gala',
    subtitle: 'Lana virgen con botonadura labrada y bordados inspirados en la herencia charra.',
    editorialProvenance: 'Septiembre · Look 02',
    availability: 'in-stock'
  },
  {
    id: 'andina-01',
    name: 'Vestido Rebozo Seda Esmeralda',
    brand: 'Andina',
    category: 'Ropa',
    family: 'mujer',
    price: 1980,
    priceFormatted: '$1,980 MXN',
    colors: 'Verde Esmeralda / Olivo',
    sizes: ['CH', 'M', 'G'],
    image: 'https://image.qwenlm.ai/public_source/ba5bbbd1-0f81-4568-a13e-b8a4583800d2/1ff7bfbd5-5b17-41cb-91a1-7b4c775da3e5.png',
    tag: 'Seda Pura',
    subtitle: 'Seda natural fluida de caída libre con empuntado tradicional en flecos.',
    editorialProvenance: 'Septiembre · Look 03',
    availability: 'limited'
  },
  {
    id: 'norte-01',
    name: 'Chaqueta Denim Vintage Roma',
    brand: 'Norte',
    category: 'Ropa',
    family: 'hombre',
    price: 1350,
    priceFormatted: '$1,350 MXN',
    colors: 'Indigo Lavado / Costura Cobriza',
    sizes: ['S', 'M', 'L', 'XL'],
    image: 'https://image.qwenlm.ai/public_source/ba5bbbd1-0f81-4568-a13e-b8a4583800d2/111e12a6d-d096-4f3e-8057-da74dbd6bfb5.png',
    tag: 'Roma Norte',
    subtitle: 'Mezclilla pesada 14oz con tratamiento lavado a la piedra y bolsillos interiores.',
    editorialProvenance: 'Octubre · Look 01',
    availability: 'in-stock'
  },
  {
    id: 'bruma-01',
    name: 'Gorra Marinera Pana & Lana',
    brand: 'Bruma',
    category: 'Accesorios',
    family: 'unisex',
    price: 520,
    priceFormatted: '$520 MXN',
    colors: 'Café Tabaco / Negro',
    image: 'https://image.qwenlm.ai/public_source/ba5bbbd1-0f81-4568-a13e-b8a4583800d2/1ba131494-cfc9-4674-ae32-da567f8cb5e2.png',
    tag: 'Clásico',
    subtitle: 'Pana de algodón acanalada con forro de satén y visera estructurada.',
    editorialProvenance: 'Octubre · Look 02',
    availability: 'in-stock'
  },
  {
    id: 'lluvia-lab-01',
    name: 'Poncho Storm Breaker Pro',
    brand: 'Lluvia Lab',
    category: 'Ropa',
    family: 'unisex',
    price: 1150,
    priceFormatted: '$1,150 MXN',
    colors: 'Grafito / Reflectivo Amarillo',
    sizes: ['S/M', 'L/XL'],
    image: 'https://image.qwenlm.ai/public_source/ba5bbbd1-0f81-4568-a13e-b8a4583800d2/137b0daca-0ff3-4489-b0bb-75f759fe7fda.png',
    isNew: true,
    tag: 'Técnico',
    subtitle: 'Ripstop impermeable 10,000mm con costuras termoselladas y capucha ajustable.',
    editorialProvenance: 'Agosto · Drop Técnico',
    availability: 'in-stock'
  },
  {
    id: 'terra-02',
    name: 'Botines Chelsea Caucho Crema',
    brand: 'Terra',
    category: 'Calzado',
    family: 'mujer',
    price: 1280,
    priceFormatted: '$1,280 MXN',
    colors: 'Crema Arena / Elástico Negro',
    sizes: ['23 MX', '24 MX', '25 MX', '26 MX'],
    image: 'https://image.qwenlm.ai/public_source/ba5bbbd1-0f81-4568-a13e-b8a4583800d2/1b997c99b-506e-49b7-8179-b71cf840e1cd.png',
    isNew: true,
    tag: 'Top Ventas',
    subtitle: 'Acabado mate aterciopelado fácil de limpiar con elásticos laterales reforzados.',
    editorialProvenance: 'Agosto · Calzado 02',
    availability: 'in-stock'
  },
  {
    id: 'august-look',
    name: 'Look Monzón Tapatío',
    brand: 'Manta',
    category: 'Ropa',
    family: 'unisex',
    price: 2890,
    priceFormatted: '$2,890 MXN',
    colors: 'Mostaza / Teal / Terracota',
    sizes: ['CH', 'M', 'G'],
    image: '/assets/editorial/august-cover.png',
    isNew: true,
    tag: 'Look Editorial',
    subtitle: 'La composición completa de la primera edición de MANTA.',
    editorialProvenance: 'Agosto · La ciudad después del agua',
    releaseEditionId: 'august',
    // Editorial composition only: it is not a purchasable family bundle.
    storeVisible: false,
    sourceStoryId: 'august-rain',
    availability: 'limited'
  },
  {
    id: 'august-bolsa',
    name: 'Bolsa de Diario Cantera',
    brand: 'Valle',
    category: 'Accesorios',
    family: 'unisex',
    price: 890,
    priceFormatted: '$890 MXN',
    colors: 'Terracota / Café',
    image: '/assets/editorial/products/overshirt-terracotta.png',
    tag: 'Oficio',
    subtitle: 'Bolsa suave de uso diario con textura inspirada en piedra y tierra mojada.',
    editorialProvenance: 'Agosto · Oficio que se lleva',
    releaseEditionId: 'august',
    storeVisible: true,
    sourceStoryId: 'august-oficio',
    availability: 'in-stock'
  },
  {
    id: 'august-bolso-azul',
    name: 'Bolso Azul de Noche',
    brand: 'Manta',
    category: 'Accesorios',
    family: 'mujer',
    price: 1120,
    priceFormatted: '$1,120 MXN',
    colors: 'Azul profundo / Metal cálido',
    image: '/assets/editorial/products/bolso-azul-noche.png',
    tag: 'Noche',
    subtitle: 'Silueta compacta para llevar la noche entre una mesa y otra.',
    editorialProvenance: 'Agosto · Noche de barrio',
    releaseEditionId: 'august',
    storeVisible: true,
    sourceStoryId: 'august-noche',
    availability: 'limited'
  },
  {
    id: 'august-bolso-cafe',
    name: 'Bolso Café de Terraza',
    brand: 'Manta',
    category: 'Accesorios',
    family: 'unisex',
    price: 1240,
    priceFormatted: '$1,240 MXN',
    colors: 'Café cacao / Metal cálido',
    image: '/assets/editorial/products/bolso-cafe-terraza-editorial.png',
    tag: 'Objeto de escena',
    subtitle: 'Bolso estructurado para pasar de la calle a la reunión.',
    editorialProvenance: 'Agosto · Noche de barrio',
    releaseEditionId: 'august',
    storeVisible: true,
    sourceStoryId: 'august-noche',
    availability: 'in-stock'
  },
  {
    id: 'august-capa',
    name: 'Capa Ligera de Lluvia',
    brand: 'Lluvia Lab',
    category: 'Abrigos',
    family: 'unisex',
    price: 1350,
    priceFormatted: '$1,350 MXN',
    colors: 'Teal / Forro Óxido',
    sizes: ['CH', 'M', 'G'],
    image: '/assets/editorial/products/jacket-teal.png',
    tag: 'Capa',
    subtitle: 'Una capa flexible para caminar entre lluvia, sombra y sol.',
    editorialProvenance: 'Agosto · Oficio que se lleva',
    releaseEditionId: 'august',
    storeVisible: true,
    sourceStoryId: 'august-oficio',
    availability: 'in-stock'
  },
  {
    id: 'august-bordado',
    name: 'Camisa Bordado de Barrio',
    brand: 'Manta',
    category: 'Camisas',
    family: 'mujer',
    price: 1180,
    priceFormatted: '$1,180 MXN',
    colors: 'Crema / Hilo Terracota',
    sizes: ['CH', 'M', 'G'],
    image: '/assets/editorial/products/overshirt-terracotta.png',
    isNew: true,
    tag: 'Editorial',
    subtitle: 'Camisa de algodón con un gesto de color hecho para repetirse.',
    editorialProvenance: 'Agosto · Oficio que se lleva',
    releaseEditionId: 'august',
    storeVisible: true,
    sourceStoryId: 'august-oficio',
    availability: 'in-stock'
  },
  {
    id: 'august-chaqueta',
    name: 'Chaqueta Teal de Noche',
    brand: 'Norte',
    category: 'Abrigos',
    family: 'hombre',
    price: 1690,
    priceFormatted: '$1,690 MXN',
    colors: 'Teal Profundo / Óxido',
    sizes: ['CH', 'M', 'G', 'XG'],
    image: '/assets/editorial/products/jacket-teal.png',
    tag: 'Noche',
    subtitle: 'Capa ligera con forro cálido para la última hora de la tarde.',
    editorialProvenance: 'Agosto · Noche de barrio',
    releaseEditionId: 'august',
    storeVisible: true,
    sourceStoryId: 'august-noche',
    availability: 'limited'
  },
  {
    id: 'august-punto',
    name: 'Punto Bruma de Temporada',
    brand: 'Bruma',
    category: 'Ropa',
    family: 'unisex',
    price: 980,
    priceFormatted: '$980 MXN',
    colors: 'Teal / Arena',
    sizes: ['CH', 'M', 'G'],
    image: '/assets/editorial/products/jacket-teal.png',
    tag: 'Punto',
    subtitle: 'Textura suave para una noche fresca y una ciudad que sigue caminando.',
    editorialProvenance: 'Agosto · Noche de barrio',
    releaseEditionId: 'august',
    storeVisible: true,
    sourceStoryId: 'august-noche',
    availability: 'in-stock'
  },
  {
    id: 'august-sneakers',
    name: 'Tenis Paso Mojado',
    brand: 'Terra',
    category: 'Calzado',
    family: 'unisex',
    price: 1240,
    priceFormatted: '$1,240 MXN',
    colors: 'Humo / Ámbar',
    sizes: ['24 MX', '25 MX', '26 MX', '27 MX', '28 MX'],
    image: '/assets/editorial/products/boots-smoke.png',
    tag: 'Urbano',
    subtitle: 'Suela firme y silueta limpia para cruzar la ciudad después de la lluvia.',
    editorialProvenance: 'Agosto · Noche de barrio',
    releaseEditionId: 'august',
    storeVisible: true,
    sourceStoryId: 'august-noche',
    availability: 'in-stock'
  },
  {
    id: 'august-acento',
    name: 'Pañoleta Ruta de Agua',
    brand: 'Manta',
    category: 'Accesorios',
    family: 'unisex',
    price: 420,
    priceFormatted: '$420 MXN',
    colors: 'Óxido / Mostaza',
    image: '/assets/editorial/products/umbrella-mustard.png',
    tag: 'Acento',
    subtitle: 'Un pequeño golpe de color para llevar la historia contigo.',
    editorialProvenance: 'Agosto · Noche de barrio',
    releaseEditionId: 'august',
    storeVisible: true,
    sourceStoryId: 'august-noche',
    availability: 'in-stock'
  },
  {
    id: 'august-kids-raincoat',
    name: 'Impermeable Nube Amarilla',
    brand: 'Manta',
    category: 'Ropa',
    family: 'ninos',
    price: 790,
    priceFormatted: '$790 MXN',
    colors: 'Mostaza / Teal',
    sizes: ['4A', '6A', '8A', '10A'],
    image: '/assets/editorial/products/ninos-impermeable-amarillo.png',
    isNew: true,
    tag: 'Niños',
    subtitle: 'Impermeable ligero para convertir el trayecto de lluvia en una pequeña aventura.',
    editorialProvenance: 'Agosto · La ciudad después del agua · Niños',
    releaseEditionId: 'august',
    storeVisible: true,
    sourceStoryId: 'august-rain',
    availability: 'in-stock'
  },
  {
    id: 'august-kids-boots',
    name: 'Botas Charco Teal',
    brand: 'Terra',
    category: 'Calzado',
    family: 'ninos',
    price: 620,
    priceFormatted: '$620 MXN',
    colors: 'Teal / Terracota',
    sizes: ['18 MX', '19 MX', '20 MX', '21 MX'],
    image: '/assets/editorial/products/ninos-botas-charco.png',
    tag: 'Niños',
    subtitle: 'Bota flexible de lluvia con agarre para caminar, saltar y volver a casa.',
    editorialProvenance: 'Agosto · La ciudad después del agua · Niños',
    releaseEditionId: 'august',
    storeVisible: true,
    sourceStoryId: 'august-rain',
    availability: 'in-stock'
  },
  {
    id: 'august-kids-backpack',
    name: 'Mochila Nube de Camino',
    brand: 'Manta',
    category: 'Mochilas',
    family: 'ninos',
    price: 690,
    priceFormatted: '$690 MXN',
    colors: 'Óxido / Teal',
    sizes: ['Única'],
    image: '/assets/editorial/products/ninos-mochila-nube.png',
    tag: 'Niños',
    subtitle: 'Una mochila compacta para llevar lo necesario durante la jornada.',
    editorialProvenance: 'Agosto · La ciudad después del agua · Niños',
    releaseEditionId: 'august',
    storeVisible: true,
    sourceStoryId: 'august-rain',
    availability: 'in-stock'
  },
  {
    id: 'august-kids-plush',
    name: 'Compañero Ajolote de Lluvia',
    brand: 'Manta',
    category: 'Peluches',
    family: 'ninos',
    price: 440,
    priceFormatted: '$440 MXN',
    colors: 'Terracota / Teal',
    sizes: ['Única'],
    image: '/assets/editorial/products/ninos-peluche-ajolote.png',
    tag: 'Niños',
    subtitle: 'Un pequeño acompañante suave para la pausa entre una escena y otra.',
    editorialProvenance: 'Agosto · La ciudad después del agua · Niños',
    releaseEditionId: 'august',
    storeVisible: true,
    sourceStoryId: 'august-rain',
    availability: 'in-stock'
  },
  {
    id: 'august-baby-body',
    name: 'Body Cielo de Algodón',
    brand: 'Manta',
    category: 'Ropa',
    family: 'bebe',
    price: 520,
    priceFormatted: '$520 MXN',
    colors: 'Crema / Cielo',
    sizes: ['3-6M', '6-12M', '12-18M'],
    image: '/assets/editorial/products/bebe-body-cielo.png',
    tag: 'Bebé',
    subtitle: 'Una pieza suave para los primeros días de lluvia y de luz.',
    editorialProvenance: 'Agosto · La ciudad después del agua · Bebé',
    releaseEditionId: 'august',
    storeVisible: true,
    sourceStoryId: 'august-rain',
    availability: 'in-stock'
  }
];

export const KIDS_IMAGES = {
  beaglePortada: 'https://image.qwenlm.ai/public_source/881fbe0f-c2f7-44ca-82ed-bb676fcd173f/1464535a2-5205-402d-8676-4353da186a10.png',
  comicBento: 'https://image.qwenlm.ai/public_source/881fbe0f-c2f7-44ca-82ed-bb676fcd173f/10067a07b-845c-4ea4-847c-155ae0ecd6ae.png',
  raincoatYellow: 'https://image.qwenlm.ai/public_source/881fbe0f-c2f7-44ca-82ed-bb676fcd173f/11b855d6b-6aae-429d-b242-ebfe563edcb1.png',
  yellowBoots: 'https://image.qwenlm.ai/public_source/881fbe0f-c2f7-44ca-82ed-bb676fcd173f/1721519be-c2d3-4153-be0f-be6761ea9276.png',
  yellowHat: 'https://image.qwenlm.ai/public_source/881fbe0f-c2f7-44ca-82ed-bb676fcd173f/1714602ab-f048-4b51-a7c8-3bccb9cf133e.png',
  birdUmbrella: 'https://image.qwenlm.ai/public_source/881fbe0f-c2f7-44ca-82ed-bb676fcd173f/1592b0d6e-0c88-4ce4-aa49-42906da3c48b.png',
  mochila: 'https://image.qwenlm.ai/public_source/881fbe0f-c2f7-44ca-82ed-bb676fcd173f/14c598cd6-605e-4199-a73c-2dc5b388a37d.png',
  peluche: 'https://image.qwenlm.ai/public_source/881fbe0f-c2f7-44ca-82ed-bb676fcd173f/1aca10020-0cab-4344-a56e-f33560976c64.png',
  knit: 'https://image.qwenlm.ai/public_source/881fbe0f-c2f7-44ca-82ed-bb676fcd173f/1f34a9421-750d-4350-915c-9b879b02ae7d.png',
  ninos: 'https://image.qwenlm.ai/public_source/881fbe0f-c2f7-44ca-82ed-bb676fcd173f/167a19204-d627-4d5b-a3e3-3ba9b77258b3.png',
  raincoatOxido: 'https://image.qwenlm.ai/public_source/881fbe0f-c2f7-44ca-82ed-bb676fcd173f/10bb633fe-df55-42a5-8f13-5b397180f25b.png',
  bebe: 'https://image.qwenlm.ai/public_source/881fbe0f-c2f7-44ca-82ed-bb676fcd173f/13df52b6a-56e8-4279-a148-ee145ac4c371.png',
  sneakers: 'https://image.qwenlm.ai/public_source/881fbe0f-c2f7-44ca-82ed-bb676fcd173f/167ea1c1a-0b87-4a55-8a23-fa5204e558c3.png',
  calcetines: 'https://image.qwenlm.ai/public_source/881fbe0f-c2f7-44ca-82ed-bb676fcd173f/1311eaa51-a26f-4783-86cf-421a41304ac9.png',
  tiraEscena: 'https://image.qwenlm.ai/public_source/881fbe0f-c2f7-44ca-82ed-bb676fcd173f/1559830b2-751c-4f83-93dc-540952cdafda.png'
};

export const KIDS_BEAGLE_PRODUCTS: StoreProduct[] = [
  {
    id: 'kids-beagle-01',
    name: 'Raincoat Amarillo Beagle',
    brand: 'Manta',
    category: 'Ropa',
    family: 'ninos',
    price: 65,
    priceFormatted: '$65 USD',
    colors: 'Amarillo / botones rojos',
    sizes: ['4', '6', '8', '10'],
    image: KIDS_IMAGES.raincoatYellow,
    isNew: true,
    guaf: true,
    tag: 'Look Referencia',
    subtitle: 'Raincoat amarillo brillante con botones rojos, capucha ribeteada y corte impermeable.',
    editorialProvenance: 'Colección Beagle · Kids 06',
    availability: 'in-stock'
  },
  {
    id: 'kids-beagle-02',
    name: 'Knit Beagle Orejas',
    brand: 'Bruma',
    category: 'Ropa',
    family: 'ninos',
    price: 46,
    priceFormatted: '$46 USD',
    colors: 'Avena / capucha',
    sizes: ['4', '6', '8', '10'],
    image: KIDS_IMAGES.knit,
    guaf: true,
    tag: 'Tejido Suave',
    subtitle: 'Suéter de lana peinada hipoalergénica con silueta de orejas beagle en capucha.',
    editorialProvenance: 'Colección Beagle · Kids 06',
    availability: 'in-stock'
  },
  {
    id: 'kids-beagle-03',
    name: 'Dúo Kids Paraguas',
    brand: 'Norte',
    category: 'Ropa',
    family: 'ninos',
    price: 85,
    priceFormatted: '$85 USD',
    colors: 'Óxido / verde',
    sizes: ['4', '6', '8', '10'],
    image: KIDS_IMAGES.ninos,
    tag: 'Set Dúo',
    subtitle: 'Conjunto coordinado impermeable para hermanos o amigos bajo la lluvia.',
    editorialProvenance: 'Colección Beagle · Kids 06',
    availability: 'in-stock'
  },
  {
    id: 'kids-beagle-04',
    name: 'Raincoat Óxido Kids',
    brand: 'Norte',
    category: 'Ropa',
    family: 'ninos',
    price: 70,
    priceFormatted: '$70 USD',
    colors: 'Óxido',
    sizes: ['4', '6', '8', '10'],
    image: KIDS_IMAGES.raincoatOxido,
    tag: 'Clásico Lluvia',
    subtitle: 'Chubasquero técnico en tono óxido con sellado térmico y broches de seguridad.',
    editorialProvenance: 'Colección Beagle · Kids 06',
    availability: 'in-stock'
  },
  {
    id: 'kids-beagle-05',
    name: 'Set Bebé Nube',
    brand: 'Manta',
    category: 'Ropa',
    family: 'bebe',
    price: 60,
    priceFormatted: '$60 USD',
    colors: 'Avena / mostaza',
    sizes: ['4', '6', '8', '10'],
    image: KIDS_IMAGES.bebe,
    tag: 'Primera Infancia',
    subtitle: 'Algodón orgánico afelpado con estampados de nubes y sol para días de llovizna.',
    editorialProvenance: 'Colección Beagle · Kids 06',
    availability: 'in-stock'
  },
  {
    id: 'kids-beagle-06',
    name: 'Botas Amarillas Suela Roja',
    brand: 'Manta',
    category: 'Calzado',
    family: 'ninos',
    price: 48,
    priceFormatted: '$48 USD',
    colors: 'Amarillo / suela roja',
    sizes: ['26', '28', '30', '32'],
    image: KIDS_IMAGES.yellowBoots,
    isNew: true,
    guaf: true,
    tag: 'Suela Roja',
    subtitle: 'Botas de caucho natural con contraste icónico en suela roja antideslizante.',
    editorialProvenance: 'Colección Beagle · Kids 06',
    availability: 'in-stock'
  },
  {
    id: 'kids-beagle-07',
    name: 'Sneakers Beagle Kids',
    brand: 'Bruma',
    category: 'Calzado',
    family: 'ninos',
    price: 58,
    priceFormatted: '$58 USD',
    colors: 'Blanco / bordado',
    sizes: ['26', '28', '30', '32'],
    image: KIDS_IMAGES.sneakers,
    guaf: true,
    tag: 'Urbano',
    subtitle: 'Zapatillas ligeras con ajuste elástico y bordado lateral del cachorro beagle.',
    editorialProvenance: 'Colección Beagle · Kids 06',
    availability: 'in-stock'
  },
  {
    id: 'kids-beagle-08',
    name: 'Paraguas Rojo Amigo',
    brand: 'Lluvia Lab',
    category: 'Accesorios',
    family: 'ninos',
    price: 35,
    priceFormatted: '$35 USD',
    colors: 'Rojo / mango curvo',
    sizes: ['ÚNICO'],
    image: KIDS_IMAGES.birdUmbrella,
    isNew: true,
    guaf: true,
    tag: 'Icono Colección',
    subtitle: 'Paraguas infantil con varillas flexibles anti-viento y mango curvo de fácil agarre.',
    editorialProvenance: 'Colección Beagle · Kids 06',
    availability: 'in-stock'
  },
  {
    id: 'kids-beagle-09',
    name: 'Gorro Lluvia Amarillo',
    brand: 'Lluvia Lab',
    category: 'Accesorios',
    family: 'ninos',
    price: 26,
    priceFormatted: '$26 USD',
    colors: 'Amarillo / cinta roja',
    sizes: ['ÚNICO'],
    image: KIDS_IMAGES.yellowHat,
    isNew: true,
    guaf: true,
    tag: 'Repelente',
    subtitle: 'Sombrero marinero impermeable con ribete rojo y forro interior absorbente.',
    editorialProvenance: 'Colección Beagle · Kids 06',
    availability: 'in-stock'
  },
  {
    id: 'kids-beagle-10',
    name: 'Calcetines Trío Lluvia',
    brand: 'Lluvia Lab',
    category: 'Accesorios',
    family: 'ninos',
    price: 22,
    priceFormatted: '$22 USD',
    colors: 'Rojo/amarillo/negro',
    sizes: ['ÚNICO'],
    image: KIDS_IMAGES.calcetines,
    tag: 'Pack x3',
    subtitle: 'Trío de calcetines altos de algodón peinado con soporte elástico en arco.',
    editorialProvenance: 'Colección Beagle · Kids 06',
    availability: 'in-stock'
  },
  {
    id: 'kids-beagle-11',
    name: 'Mochila Casita Roja',
    brand: 'Manta',
    category: 'Mochilas',
    family: 'ninos',
    price: 55,
    priceFormatted: '$55 USD',
    colors: 'Rojo / parche beagle',
    sizes: ['15L'],
    image: KIDS_IMAGES.mochila,
    guaf: true,
    tag: 'Edición Especial',
    subtitle: 'Mochila escolar resistente al agua con silueta de techo rojo y parche bordado.',
    editorialProvenance: 'Colección Beagle · Kids 06',
    availability: 'in-stock'
  },
  {
    id: 'kids-beagle-12',
    name: 'Peluche Beagle Lluvioso',
    brand: 'Terra',
    category: 'Peluches',
    family: 'ninos',
    price: 40,
    priceFormatted: '$40 USD',
    colors: 'Raincoat amarillo',
    sizes: ['ÚNICO'],
    image: KIDS_IMAGES.peluche,
    guaf: true,
    tag: 'Peluche 3D',
    subtitle: 'Muñeco de peluche táctil de alta suavidad con impermeable amarillo removible.',
    editorialProvenance: 'Colección Beagle · Kids 06',
    availability: 'in-stock'
  }
];

export const STORE_CATALOG_PRODUCTS: StoreProduct[] = [
  ...EDITORIAL_STORE_PRODUCTS,
  ...HOMBRE_PRODUCTS,
  ...KIDS_BEAGLE_PRODUCTS,
  {
    id: 'valle-02',
    name: 'Chubasquero Infantil Ranita',
    brand: 'Valle',
    category: 'Ropa',
    family: 'ninos',
    price: 790,
    priceFormatted: '$790 MXN',
    colors: 'Verde Pino / Amarillo Sol',
    sizes: ['4A', '6A', '8A', '10A'],
    image: 'https://image.qwenlm.ai/public_source/ba5bbbd1-0f81-4568-a13e-b8a4583800d2/1c0e12018-da51-40f4-bb31-83caa5e82f13.png',
    tag: 'Infantil',
    subtitle: 'Broches de presión seguros, visera transparente en capucha y cinta reflectante.',
    editorialProvenance: 'Colección Niños',
    availability: 'in-stock'
  },
  {
    id: 'andina-02',
    name: 'Enterizo Oso Algodón Acolchado',
    brand: 'Andina',
    category: 'Ropa',
    family: 'bebe',
    price: 640,
    priceFormatted: '$640 MXN',
    colors: 'Caramelo Suave / Crudo',
    sizes: ['3-6M', '6-12M', '12-18M'],
    image: 'https://image.qwenlm.ai/public_source/ba5bbbd1-0f81-4568-a13e-b8a4583800d2/1918f64ff-f2f2-49a4-9534-4850ea64937b.png',
    tag: 'Bebé',
    subtitle: 'Doble capa de algodón pima térmico con cremallera diagonal suave de cuello a pie.',
    editorialProvenance: 'Colección Bebé',
    availability: 'in-stock'
  }
];

export const WEEKLY_DROP_PRODUCTS: StoreProduct[] = [
  KIDS_BEAGLE_PRODUCTS[0], // Raincoat Amarillo Beagle
  KIDS_BEAGLE_PRODUCTS[5], // Botas Amarillas Suela Roja
  KIDS_BEAGLE_PRODUCTS[10], // Mochila Casita Roja
  KIDS_BEAGLE_PRODUCTS[11]  // Peluche Beagle Lluvioso
].filter(Boolean);

export const getCategoryCount = (familyId: 'mujer' | 'hombre' | 'ninos' | 'bebe'): number => {
  return STORE_CATALOG_PRODUCTS.filter((p) => p.family === familyId).length;
};

export const STORE_CATEGORIES: StoreCategoryItem[] = [
  {
    id: 'mujer',
    title: 'Mujer',
    chip: 'COLECCIÓN MUJER',
    countLabel: `${getCategoryCount('mujer')} prendas`,
    image: 'https://image.qwenlm.ai/public_source/ba5bbbd1-0f81-4568-a13e-b8a4583800d2/1b997c99b-506e-49b7-8179-b71cf840e1cd.png',
    accent: '#f2c14e',
    tagline: 'Sastrería contemporánea y capas de lluvia con cortes envolventes.'
  },
  {
    id: 'hombre',
    title: 'Hombre',
    chip: 'EDITORIAL LLUVIA · HOMBRE 05',
    countLabel: `${getCategoryCount('hombre')} prendas`,
    image: HOMBRE_IMAGES.hombre,
    accent: '#2f8f8a',
    tagline: 'Sastrería suave, probador digital con fotos reales y la fila de mochilas.'
  },
  {
    id: 'ninos',
    title: 'Niños (Beagle 3D)',
    chip: 'COLECCIÓN KIDS · LOOK BEAGLE',
    countLabel: `${getCategoryCount('ninos')} piezas`,
    image: KIDS_IMAGES.beaglePortada,
    accent: '#f2c14e',
    tagline: 'Colección Beagle: peluche 3D, impermeable amarillo y paraguas rojo.'
  },
  {
    id: 'bebe',
    title: 'Bebé',
    chip: 'PRIMERA INFANCIA',
    countLabel: `${getCategoryCount('bebe')} prendas`,
    image: KIDS_IMAGES.bebe,
    accent: '#d9a441',
    tagline: 'Algodón orgánico hipoalergénico y botines de lana suave.'
  }
];
